// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Movie_Watchlist_web_api__angular___core_net_web_api_.DBConstructor;

#nullable disable

namespace Movie_Watchlist_web_api__angular___core_net_web_api_.Migrations
{
    [DbContext(typeof(DB_Constructor))]
    partial class DB_ConstructorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Movie_Watchlist_web_api__angular___core_net_web_api_.DBModel.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserData");
                });

            modelBuilder.Entity("Movie_Watchlist_web_api__angular___core_net_web_api_.DBModel.UserMovies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieRating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MovieWatched")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("UserMovies");
                });

            modelBuilder.Entity("Movie_Watchlist_web_api__angular___core_net_web_api_.DBModel.UserMovies", b =>
                {
                    b.HasOne("Movie_Watchlist_web_api__angular___core_net_web_api_.DBModel.User", null)
                        .WithMany("UserMovies")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Movie_Watchlist_web_api__angular___core_net_web_api_.DBModel.User", b =>
                {
                    b.Navigation("UserMovies");
                });
#pragma warning restore 612, 618
        }
    }
}
